name: Deploy nuxt app to GitHub Pages

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
    - name: Build and Deploy
      uses: JamesIves/setpage-deploy-action@releases/v3
      id: deployment
      with:
        token: '${{ secrets.TOKEN_GITHUB }}'
        environment-url: http://antil_test.com
        environment: production
        BASE_BRANCH: develop
        BRANCH: gh-pages
        FOLDER: .nuxt
